# Class-1
## Itroduction to opencv

In [1]:
import cv2

In [2]:
img = cv2.imread("./picture/img1.jpg")  # image read
cv2.imshow("Wscube Tech",img)   # images show
cv2.waitKey(0)                  # image frame wait  time - ms and 0 pass keyboard any key pass
cv2.destroyAllWindows()         # all windows close
# cv2.destroyWindow()           # only one window close

In [ ]:
img = cv2.imread("./picture/img1.jpg")  # image read
cv2.imshow("Wscube Tech",img)   # images show
cv2.imshow("Wscube Tech1",img)  # images show
cv2.waitKey(0)                  # image frame wait  time - ms and 0 pass keyboard any key pass
cv2.destroyAllWindows()         # all windows close
# cv2.destroyWindow("Wscube Tech1")  

# Class-2
## Show Multiple Image and Slide Show

In [5]:
import cv2
import numpy as np
import os

In [3]:
img = cv2.imread("./picture/img3.png")
# To resize the image
re_img = cv2.resize(img,(500,300))

cv2.imshow("Heart",re_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [65]:
# [[],[]]
h = np.array([1,2,3,1,2,3])
np.hstack((h,h))

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [64]:
v = np.array([1,2,3,1,2,3])
np.vstack((v,v))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [66]:
img = cv2.imread("./picture/img3.png")
print(img) # RGB and Grayscale

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [22]:
img = cv2.imread("./picture/img1.jpg")
# To resize the image
re_img = cv2.resize(img,(300,300))

h = np.hstack((re_img,re_img))
v = np.vstack((h,h))

cv2.imshow("Heart",v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
list_name = os.listdir(r"F:\DATA SCIENCE 2\IMAGE PROCESSING\Open cv\picture\picture2")
list_name

['roi_demo2.jpg',
 'saeed1.png',
 'saeed_1.png',
 'saeed_new1.jpeg',
 'SharedScreenshot.jpg',
 'sudoku.png',
 'temp.jpg',
 'test12.jpg',
 'test21.jpg']

In [31]:
for name in list_name:
    path = "F:\DATA SCIENCE 2\IMAGE PROCESSING\Open cv\picture\picture2"
    img_name = path + "\\" + name
    img = cv2.imread(img_name)
    img = cv2.resize(img,(500,500))
    cv2.imshow("Heart",img)
    cv2.waitKey(1000)

cv2.destroyAllWindows()

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Saeed\AppData\Local\Temp\ipykernel_10244\1545906638.py:2: SyntaxWarning: invalid escape sequence '\D'
  path = "F:\DATA SCIENCE 2\IMAGE PROCESSING\Open cv\picture\picture2"


# Paractice Part

In [25]:
import cv2
import os

In [26]:
img = cv2.imread('./picture/img1.jpg')

re_img = cv2.resize(img,(300,300))

h = np.hstack((re_img,re_img,re_img))
v = np.vstack((h,h))


cv2.imshow('heart',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
list_name = os.listdir(r'F:\DATA SCIENCE 2\IMAGE PROCESSING\Open cv\picture\picture2')
list_name

['roi_demo2.jpg',
 'saeed1.png',
 'saeed_1.png',
 'saeed_new1.jpeg',
 'SharedScreenshot.jpg',
 'sudoku.png',
 'temp.jpg',
 'test12.jpg',
 'test21.jpg']

In [28]:
for name in list_name:
    path = 'F:\DATA SCIENCE 2\IMAGE PROCESSING\Open cv\picture\picture2'
    img = path + "\\" + name
    img = cv2.imread(img)
    re_image = cv2.resize(img,(300,300))
    cv2.imshow('slide',re_image)
    cv2.waitKey(1000)

cv2.destroyAllWindows()


<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\Saeed\AppData\Local\Temp\ipykernel_10244\705985428.py:2: SyntaxWarning: invalid escape sequence '\D'
  path = 'F:\DATA SCIENCE 2\IMAGE PROCESSING\Open cv\picture\picture2'


# **class-3**
## Read and Show Image (imread(),imshow())

In [32]:
import cv2
import numpy as np

In [33]:
img = cv2.imread('./picture/img1.jpg',0)# flage 1 or 0 for grayscale
print(img.shape)
img = cv2.resize(img,(500,500))
cv2.imshow('heart',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(828, 1080)


In [34]:
img = cv2.imread('./picture/img1.jpg',1)# flage 1 or 0 for grayscale
print(img.shape)
img = cv2.resize(img,(500,500))
cv2.imshow('heart',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(828, 1080, 3)


In [35]:
img = cv2.imread('./picture/img1.jpg',-1)# flage 1 or 0 for grayscale
print(img.shape)
img = cv2.resize(img,(500,500))
cv2.imshow('heart',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(828, 1080, 3)


In [36]:
img = cv2.imread('./picture/img1.jpg',-1)# flage 1 or 0 for grayscale
print(img.shape)
img = cv2.resize(img,(500,500))
cv2.imshow('heart',img) 

cv2.waitKey(0)
cv2.destroyAllWindows()

(828, 1080, 3)


# **class-4**
## Text Over a image


In [37]:
import cv2
import numpy as np

In [41]:
img_get = cv2.imread('./picture/img1.jpg')
img_get = cv2.resize(img_get,(600,600))



txt = cv2.putText(img = img_get, 
text = "The Heart",
org = (50,100),
fontFace = cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color = (0,0,255),
thickness = 3,
lineType = cv2.LINE_8,
bottomLeftOrigin = False
)


txt = cv2.putText(img = txt, 
text = "The Heart",
org = (50,110),
fontFace = cv2.FONT_HERSHEY_DUPLEX,
fontScale = 3,
color = (255,0,0),
thickness = 3,
lineType = cv2.LINE_8,
bottomLeftOrigin = True
)


cv2.imshow('img',txt)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# img, text, org, fontFace, fontScale, color[, thickness, lineType, bottomLeftOrigin]

# **class-5**
## Draw Line and Rectangle on Image

In [51]:
import cv2
import numpy as np

## Line

In [42]:
old_img = cv2.imread('./picture/img9.jpeg')
old_img = cv2.resize(old_img,(500,700))

new_img = cv2.line(img = old_img, pt1=(200,270),pt2=(140,265),color=(0,255,0),thickness=4,lineType=4)

cv2.imwrite('./picture/saeed_new1.jpeg',new_img)
cv2.imshow("img",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Rectangle

In [43]:
old_img = cv2.imread('./picture/img3.png')
old_img = cv2.resize(old_img,(500,700))

txt = cv2.putText(img=old_img,text='Saeed',org=(100,190), fontFace=1, fontScale=1,color=(0,0,255),thickness=1,lineType=16,bottomLeftOrigin=False)

new_img = cv2.rectangle(img = txt, pt1=(200,360),pt2=(100,195),color=(0,255,0),thickness=1,lineType=4)
new_img = cv2.rectangle(img = txt, pt1=(150,175),pt2=(100,190),color=(0,255,0),thickness=1,lineType=4)


cv2.imshow("img",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-6**
## Draw Circle and Ellipse on Image

In [193]:
import cv2
import numpy as np

## Circle

In [44]:
old_img = cv2.imread("./picture/img2.png")
old_img = cv2.resize(old_img,(500,600))

new_img = cv2.circle(img=old_img,center=(265,80),radius=85,color=(0,255,0),thickness=4,lineType=16)# -1 is for filling circle



cv2.imshow("img",new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## Ellipse

In [45]:
old_img = cv2.imread("./picture/img2.png")
old_img = cv2.resize(old_img,(500,600))

txt_img = cv2.putText(img=old_img,text='nasal',org=(300,135),fontFace=2,fontScale=1,color=(0,255,0),thickness=1,lineType=16,bottomLeftOrigin=False)

new_img = cv2.ellipse(img=old_img,center=(290,115),axes=(40,60),angle=50,startAngle=0,endAngle=320,color=(0,255,0),thickness=4,lineType=16)# -1 is for filling circle



cv2.imshow("img",txt_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **paractice**

In [2]:
import cv2

In [46]:
img = cv2.imread('./picture/img9.jpeg',1)



txt_img = cv2.putText(img=img,
text="M Saeed",
org=(360,430),
fontFace=cv2.FONT_HERSHEY_DUPLEX,
fontScale=1,
color=(0,0,255),
thickness=1,
lineType=3,
bottomLeftOrigin=False
)

new_img = cv2.line(img = txt_img,
pt1=(295,330),
pt2=(400,300),
color=(255,0,0),
thickness=4,
lineType=4
)

new_image1 = cv2.rectangle(img = txt_img, pt1=(365,440),pt2=(535, 679),color=(0,255,0),thickness=3,lineType=4)
# new_image1 = cv2.rectangle(img = re_img, pt1=(382, 515),pt2=(516, 652),color=(0,255,0),thickness=1,lineType=4)

cv2.imshow('img',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [47]:
img = cv2.imread('./picture/img9.jpeg',1)
re_img = cv2.resize(img,(800,800))


txt_img = cv2.putText(img=re_img,text="Saeed",org=(295,270),color=(0,0,255),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,thickness=1,lineType=3,bottomLeftOrigin=False)

new_image1 = cv2.rectangle(img = txt_img, pt1=(298, 425),pt2=(450, 275),color=(0,255,0),thickness=4,lineType=4)

cv2.imshow('img',new_image1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **Ellipse**

In [48]:
img = cv2.imread('picture/img8.jpeg')
re_image = cv2.resize(img,(600,800))


new_img = cv2.ellipse(img = re_image,center=(390,230),axes=(150,200),angle=30,startAngle=0,endAngle=-349,color=(0,255,0),thickness=2,lineType=16)

new_img1 = cv2.putText(img = new_img,text='saeed',org=(470,330),fontFace=cv2.FONT_HERSHEY_DUPLEX,fontScale=1,lineType=16,thickness=2,color=(0,0,255))


cv2.imshow('the img',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
img.shape

(1030, 538, 3)

# **circle & ellips**


In [49]:
img = cv2.imread('picture/img7.jpeg')
re_img = cv2.resize(img,(900,500))


# circle_img = cv2.circle(img=re_img,radius=95,color=(0,0,255),lineType=16,thickness=4,center=(520,230))
txt_img = cv2.putText(img = re_img,text='Marwan',org=(580,245),lineType=16,fontFace=cv2.FONT_HERSHEY_DUPLEX,thickness=2,fontScale=1,color=(0,0,255))
ellip_img = cv2.ellipse(img=txt_img,center=(530,210),axes=(80,150),angle=5,startAngle=0,endAngle=-345,lineType=16,thickness=4,color=(0,255,0))

cv2.imshow('Marwan',ellip_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-7**
## Draw a ploygon

In [1]:
import cv2
import numpy as np

In [50]:
old_img = cv2.imread('picture/img9.jpeg')
re_img = cv2.resize(old_img,(500,500))

new_img = cv2.polylines(img=re_img,pts=[np.array([[200,100],[200,50]])],color=(0,255,0),isClosed=True,thickness=4,lineType=16)

cv2.imshow('saeed',re_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-8**
## Artihmetic Operations on Images using OpenCV

In [15]:
import cv2
import numpy as np

In [54]:
img1 = cv2.imread('picture/img9.jpeg')
img2 = cv2.imread('picture/img8.jpeg')

img1 = cv2.resize(img1,(500,500))
img2 = cv2.resize(img2,(500,500))

new_img = cv2.addWeighted(img1,0.5,img2,1,1)
# new_img = cv2.subtract(img2,img1)

cv2.imshow('conctinate',new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-9**
## Bitwise Operation on Images using OpenCV (Bitwise Operation on Binary Images)


In [1]:

import cv2
import numpy as np

In [56]:
img1 = cv2.imread('picture/img11.jpeg')
img2 = cv2.imread('picture/img13.jpg')

img1 = cv2.resize(img1,(300,300))
img2 = cv2.resize(img2,(300,300))

new = cv2.bitwise_and(img1,img2)
# new = cv2.bitwise_or(img1,img2)
# new = cv2.bitwise_xor(img1,img2)
# new = cv2.bitwise_not(img1)
# new1 = cv2.bitwise_not(img2)

h = np.hstack((img1,new))
h1 = np.hstack((img2,new))

v = np.vstack((h,h1))

cv2.imshow('and',v)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [57]:
img1 = cv2.imread('picture/img9.jpeg')
img2 = cv2.imread('picture/img8.jpeg')


img1 = cv2.resize(img1,(300,300))
img2 = cv2.resize(img2,(300,300))



new = cv2.bitwise_and(img1,img2)

h = np.hstack((img1,img2,new))

cv2.imshow('and',h)

cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-10**
## Edge Dectection using OpenCV

In [22]:
import cv2
import numpy as np

In [59]:
img = cv2.imread('picture/img8.jpeg')

img1 = cv2.resize(img,(500,500))
print(img.shape)

new_img = cv2.Canny(img1,100,100,apertureSize=5,L2gradient=True)

# h = np.hstack((new_img))

cv2.imshow('saeed',new_img)
cv2.imshow('saeed1',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1030, 538, 3)


# **class-11**
## Image Scalling Rotating using OpenCV

In [1]:
import cv2
import numpy as np

In [60]:
or_img = cv2.imread('picture/img9.jpeg')

res_img = cv2.resize(or_img,(500,500))


cv2.imshow('saeed1',or_img)
cv2.imshow('saeed',res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [61]:
or_img = cv2.imread('picture/img9.jpeg')

res_img = cv2.resize(or_img,(500,500))

w,h = res_img.shape[0],res_img.shape[1]



m = cv2.getRotationMatrix2D((w/2,h/2),90,1)
new_img = cv2.warpAffine(res_img,m,(h,w))


h = np.hstack([res_img,new_img])

cv2.imshow('saeed',h)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
or_img = cv2.imread('picture/img9.jpeg')
res_img = cv2.resize(or_img,(500,500))

w,h = res_img.shape[0] , res_img.shape[1]



m = cv2.getRotationMatrix2D((w/2,h/2),180,1)
new_img = cv2.warpAffine(res_img,m,(h,w))

h = np.hstack((res_img,new_img))

cv2.imshow('saeed',h)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-12**
## Image Blurring Using OpenCV

In [75]:
import cv2
import numpy as np

In [16]:
org_img = cv2.imread('picture/img9.jpeg')

res_img = cv2.resize(org_img,(500,500))

g = cv2.GaussianBlur(res_img,(9,9),0)
m = cv2.medianBlur(res_img,5)
b = cv2.bilateralFilter(res_img,9,100,100)

h = np.hstack((res_img,g,m,b))


cv2.imshow('saeed',h)
cv2.waitKey(0)
cv2.destroyAllWindows()


# **class-13**
## imwrite Method using OpenCV

In [35]:
import cv2
import numpy as np

In [17]:
img = cv2.imread('picture/img9.jpeg')
res_img = cv2.resize(img,(300,300))


h = cv2.hconcat([res_img,res_img])

v = np.vstack([h,h])



# cv2.imwrite('./picture/saeed_1.png',v)
cv2.imshow('saeed',v)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-14**
## MakeBorder using OpenCV

In [47]:
import cv2
import numpy as np

In [71]:
img = cv2.imread('picture/img9.jpeg')
res_img = cv2.resize(img,(500,500))

# img1 = cv2.copyMakeBorder(res_img,20,20,20,20,cv2.BORDER_CONSTANT,None,value=2)
# img_1 = cv2.resize(img1,(500,500))

# img2 = cv2.copyMakeBorder(res_img,20,20,20,20,cv2.BORDER_DEFAULT,None,value=2)
# img_2 = cv2.resize(img2,(500,500))
# h = np.hstack([res_img,img_1,img_2])
# img3 = cv2.copyMakeBorder(res_img,20,20,20,20,cv2.BORDER_REFLECT_101)
# img4 = cv2.copyMakeBorder(res_img,20,20,20,20,cv2.BORDER_REPLICATE)
# img4 = cv2.copyMakeBorder(res_img,20,20,20,20,cv2.BORDER_ISOLATED)
img5 = cv2.copyMakeBorder(res_img,20,20,20,20,cv2.BORDER_REFLECT101)


cv2.imshow('saeed',img5)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-15**
## PLAY AIDEO USING OPENCV

In [72]:
import cv2
import numpy as np

In [76]:
cap = cv2.VideoCapture('picture/video1.mp4')

while cap.isOpened():
    r,frame = cap.read()
    if r == True:
        frame = cv2.resize(frame,(600,500))
        cv2.imshow('video_play',frame)
        if cv2.waitKey(25) & 0xff == ord('p'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# **class-16**
## Capture Video From Camera Using OpenCV

In [77]:
import cv2
import numpy as np

In [ ]:
cap = cv2.VideoCapture(0)

while True:
    r,frame = cap.read()
    if r == True:
        frame = cv2.resize(frame,(500,500))
        cv2.imshow('video_play',frame)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# **class-17**
## Slow And Fast Motion Video

In [80]:
import cv2
import numpy as np

In [19]:
# Slow Motion Video

cap = cv2.VideoCapture('picture/video1.mp4')

while cap.isOpened():
    r,frame = cap.read()
    if r == True:
        frame = cv2.resize(frame,(600,500))
        cv2.imshow('video_play',frame)
        if cv2.waitKey(40) & 0xff == ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

In [18]:
# Fast Motion Video
cap = cv2.VideoCapture('picture/video1.mp4')

while cap.isOpened():
    r,frame = cap.read()
    if r == True:
        frame = cv2.resize(frame,(600,500))
        cv2.imshow('video_play',frame)
        if cv2.waitKey(1) & 0xff == ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()

# **class-18**
## Morphological Operations using OpenCV - 1

In [88]:
import cv2
import numpy as np

In [20]:
img = cv2.imread('picture/j.png')
re_img = cv2.resize(img,(500,500))

m = np.ones((15,15),np.int8)
# print(m)
er = cv2.erode(re_img,m,iterations=1)
di = cv2.dilate(re_img,m,iterations=1)

cv2.imshow('morphological',re_img)  
cv2.imshow('morphological_erode',er)
cv2.imshow('morphological_dilate',di)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-19**
## Morphological Operations using OpenCV - 2

In [3]:
import cv2
import numpy as np

In [32]:
img = cv2.imread('picture/j2.png')
img = cv2.resize(img,(500,500))


k = np.ones((20,20),np.int8)

# op = cv2.morphologyEx(img,cv2.MORPH_OPEN,k,1)
clo = cv2.morphologyEx(img,cv2.MORPH_CLOSE,k,iterations=1)


cv2.imshow('original1',img)
cv2.imshow('original',clo)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
import cv2
import numpy as np

img = cv2.imread('picture/j.png')
img = cv2.resize(img,(500,500))


k = np.ones((40,40),np.int8)
 
# gr = cv2.morphologyEx(img,cv2.MORPH_GRADIENT,k,iterations=1)
# tp = cv2.morphologyEx(img,cv2.MORPH_TOPHAT,k,iterations=1)
bp = cv2.morphologyEx(img,cv2.MORPH_BLACKHAT,k,iterations=1)


cv2.imshow('original1',img)
cv2.imshow('original',bp) 
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

# **class-20**
## Image Pyramid Using OpenCV

In [5]:
import cv2
import numpy as np

In [14]:
img = cv2.imread('picture/img9.jpeg')
print(img.shape)

# to down the image size
# new = cv2.pyrDown(img)
# print(new.shape)

new1 = cv2.pyrDown(new)
# print(new1.shape)

new2 = cv2.pyrDown(new1)
print(new2.shape)

# new3 = cv2.pyrDown(new2)
# print(new3.shape)

# to up the image size

big_img = cv2.pyrUp(new2)
print(big_img.shape)


cv2.imshow('original',img)
# cv2.imshow('original1',new)
# cv2.imshow('original2',new1)
cv2.imshow('original3',new2)
cv2.imshow('big one',big_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1280, 960, 3)
(160, 120, 3)
(320, 240, 3)
