# **class-41**
## Object Detection using Contours by Webcam

In [1]:
import cv2
import numpy as np

In [2]:
def nothing(x):
    pass

cv2.namedWindow("wscube")

cv2.createTrackbar('th','wscube',0,255,nothing)

cv2.createTrackbar('lb','wscube',0,255,nothing)
cv2.createTrackbar('lg','wscube',0,255,nothing)
cv2.createTrackbar('lr','wscube',0,255,nothing)

cv2.createTrackbar('hb','wscube',255,255,nothing)
cv2.createTrackbar('hg','wscube',255,255,nothing)
cv2.createTrackbar('hr','wscube',255,255,nothing)

cap = cv2.VideoCapture(0)

while cap.isOpened():
    r,frame = cap.read()
    if r == True:

        thr = cv2.getTrackbarPos('th','wscube')

        LB = cv2.getTrackbarPos('lb','wscube')
        LG = cv2.getTrackbarPos('lg','wscube')
        LR = cv2.getTrackbarPos('lr','wscube')

        HB = cv2.getTrackbarPos('hb','wscube')
        HG = cv2.getTrackbarPos('hg','wscube')
        HR = cv2.getTrackbarPos('hr','wscube')

        lower = np.array([LB,LG,LR])
        upper = np.array([HB,HG,HR])



        frame = cv2.flip(frame,1)
        frame = cv2.resize(frame,(400,400))
        hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)

        m = cv2.inRange(hsv,lower,upper)
        res = cv2.bitwise_and(frame,frame,mask=m)
        fr = cv2.bitwise_not(res)


        r,thi = cv2.threshold(m,thr,255,cv2.THRESH_BINARY)
        cnt,hr = cv2.findContours(thi,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

        cv2.drawContours(frame,cnt,-1,(255,0,0),2)

        cv2.imshow('thr',thi)
        cv2.imshow('res',res)
        cv2.imshow('mask',m)
        cv2.imshow('ws',frame)
        if cv2.waitKey(25) & 0xff ==ord("q"):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()


# **class-42**
## Image Background Removal Histogram

In [3]:
import cv2
import numpy as np

In [28]:
img = cv2.imread('picture/new.jpg')
img = cv2.resize(img,(500,500))
hsv = cv2.cvtColor(img,cv2.COLOR_BGR2HSV)

img1 = cv2.imread('picture/new1.jpg')
img1 = cv2.resize(img,(500,500))
hsv2 = cv2.cvtColor(img1,cv2.COLOR_BGR2HSV) 

hist = cv2.calcHist([hsv2],[0,1],None,[180,256],[0,180,0,256])
mask = cv2.calcBackProject([hsv],[0,1],hist,[0,180,0,256],1)

ker = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
mask = cv2.filter2D(mask,-1,ker)
_,thr = cv2.threshold(mask,50,255,cv2.THRESH_BINARY)

mask = cv2.merge((mask,mask,mask))

res = cv2.bitwise_or(img,mask)

cv2.imshow('res',res)
cv2.imshow('img2',img1)
cv2.imshow('sa',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-43**
## Hough Transformation Lines

In [1]:
import cv2
import numpy as np

- Maths formulas

In [ ]:
# y = mx + c
# rsin$ + rcos$ = y

In [6]:
img = cv2.imread('picture/sudoku.png')
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

edg = cv2.Canny(gry,20,250)

lines = cv2.HoughLines(edg,1,np.pi/180,200)

for r,th in lines[0]:
    a = np.cos(th)
    b = np.sin(th)

    x0 = a*r
    y0 = b*r

    x1 = int(x0 + 1000*(-b))
    y1 = int(y0+1000*(a))
    x2 = int(x0-1000*(-b))
    y2 = int(y0-1000*(a))

    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)




cv2.imshow('sudo',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
img = cv2.imread('picture/sudoku.png')
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

edg = cv2.Canny(gry,20,250)

l = cv2.HoughLinesP(edg,1,np.pi/180,200,minLineLength=180,maxLineGap=100)

for i in l:
    x1,y1,x2,y2 = i[0]
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)


cv2.imshow('sudo',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-44**
## Template Matching Using OpenCV

In [9]:
import cv2
import numpy as np

In [22]:
img = cv2.imread('picture/temp.jpg')
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

tmp = cv2.imread('picture/test21.jpg')
gry1 = cv2.cvtColor(tmp,cv2.COLOR_BGR2GRAY)

h,w = gry1.shape[0],gry1.shape[1]

res = cv2.matchTemplate(gry,gry1,cv2.TM_CCORR_NORMED)
thr = 0.95
l = np.where(res>=thr)

for i in zip(*l[::-1]):
    cv2.rectangle(img,i,(i[0]+w,i[1]+h),(0,255,0),1)




cv2.imshow('ws',res)
cv2.imshow('wscube',img)
cv2.imshow('wscube1',tmp)
cv2.waitKey(0)
cv2.destroyAllWindows()


# **class-45**
## Hough Circle Detection

In [30]:
import cv2
import numpy as np

In [41]:
img = cv2.imread('picture/circle1.png')
img = cv2.resize(img,(500,500))
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gr = cv2.medianBlur(gr,7)

c = cv2.HoughCircles(gr,cv2.HOUGH_GRADIENT,1,20,param1=50,param2=50,minRadius=0,maxRadius=0)

print(c)
data = np.uint16(np.around(c))

for x,y,r in data[0,:]:
    cv2.circle(img,(x,y),r,(255,0,0),4)



cv2.imshow('sa',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[184.5 372.5  88.9]
  [339.5 276.5  63.8]
  [196.5 219.5  20.8]
  [276.5 113.5  38. ]
  [135.5 133.5  41.2]]]


# **class-46**
## Grabcut Algorithm For background Change

In [1]:
import cv2
import numpy as np

In [15]:
img = cv2.imread('picture/Newcar.jpg')

mask1 = np.zeros(img.shape[:2],np.uint8)

bgmask = np.zeros((1,65),np.float64)*255

fgmask = np.zeros((1,65),np.float64)*255

r = [163,121,550,424]
cv2.grabCut(img,mask1,r,bgmask,fgmask,2,cv2.GC_INIT_WITH_RECT)
mask2 = np.where((mask1 == 2)|(mask1 == 0),0,1).astype("uint8")

img = img * mask2[:,:,np.newaxis]


cv2.imshow('sa',img)
cv2.waitKey(0)
cv2.destroyAllWindows()    

# **class-47**
## Video Background Removal Using Algorithm

In [20]:
import cv2
import numpy as np

In [21]:
cap = cv2.VideoCapture('picture/walking.mp4')

algo1 = cv2.createBackgroundSubtractorKNN(detectShadows=True)
algo2 = cv2.createBackgroundSubtractorMOG2(detectShadows=True)

while True:
    r,f = cap.read()
    if r == True:
        f = cv2.resize(f,(500,400))
        r1 = algo1.apply(f)
        r2 = algo2.apply(f)
        cv2.imshow('algo1',r1)
        cv2.imshow('algo2',r2)
        cv2.imshow('sa',f)

        if cv2.waitKey(50) & 0xff == ord('q'):
            break
    else:
        break


cap.release()
cv2.destroyAllWindows()

# **class-48**
## Object Tracking And Detectio

In [2]:
import cv2 
import numpy as np

In [3]:
cap = cv2.VideoCapture('picture/walking.mp4')
# cap = cv2.resize(cap,(500,400))
r,f = cap.read()
x,y,w,h = 188, 35, 188, 363
t = (x,y,w,h)
roi = f[y:y+h,x:x+w]
hsv_roi = cv2.cvtColor(roi,cv2.COLOR_BGR2HSV)
mask = cv2.inRange(hsv_roi,np.array((0.0,60.0,23.)),np.array((180.,255.,255.)))
roi_hist = cv2.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv2.normalize(roi_hist,roi_hist,0,255,cv2.NORM_MINMAX)


tr = (cv2.TERM_CRITERIA_EPS | cv2.TermCriteria_COUNT, 10,1)

while cap.isOpened():
    r,f = cap.read()
    if r == True:
        hsv_f = cv2.cvtColor(f,cv2.COLOR_BGR2HSV)
        d = cv2.calcBackProject([hsv_f],[0],roi_hist,[0,180],1)
        r,tp = cv2.meanShift(d,t,tr)
        x,y,w,h = tp
        final = cv2.rectangle(f,(x,y),(x+w,y+h),(0,0,255),4)
        # f = cv2.resize(f,(500,400))
        cv2.imshow('sa',final)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break


cap.release()
cv2.destroyAllWindows()

In [ ]:
cap = cv2.VideoCapture('picture/walking.mp4')
# cap = cv2.resize(cap,(500,400))
r,f = cap.read()
x,y,w,h = 188, 35, 188, 363
t = (x,y,w,h)
roi = f[y:y+h,x:x+w]
hsv_roi = cv2.cvtColor(roi,cv2.COLOR_BGR2HSV)
mask = cv2.inRange(hsv_roi,np.array((0.0,60.0,23.)),np.array((180.,255.,255.)))
roi_hist = cv2.calcHist([hsv_roi],[0],mask,[180],[0,180])
cv2.normalize(roi_hist,roi_hist,0,255,cv2.NORM_MINMAX)


tr = (cv2.TERM_CRITERIA_EPS | cv2.TermCriteria_COUNT, 10,1)

while cap.isOpened():
    r,f = cap.read()
    if r == True:
        hsv_f = cv2.cvtColor(f,cv2.COLOR_BGR2HSV)
        d = cv2.calcBackProject([hsv_f],[0],roi_hist,[0,180],1)
        r,tp = cv2.CamShift(d,t,tr) # only this change we use this both mean and cam shift
        x,y,w,h = tp
        final = cv2.rectangle(f,(x,y),(x+w,y+h),(0,0,255),4)
        # f = cv2.resize(f,(500,400))
        cv2.imshow('sa',final)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break


cap.release()
cv2.destroyAllWindows()

# **class-49**
## Corner Dtection Using Detection Method (Harris Corner Detection)

In [5]:
import cv2
import numpy as np

In [15]:
img = cv2.imread('picture/corrner.png')
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gr = np.float32(gr)
res = cv2.cornerHarris(gr,4,3,0.04)

res = cv2.dilate(res,None)
img[res>0.01*res.max()] = (0,0,255)


cv2.imshow('one',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
img = cv2.imread('picture/harris.jpg')
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gr = np.float32(gr)
res = cv2.cornerHarris(gr,2,3,0.04)

res = cv2.dilate(res,None)
img[res>0.01*res.max()] = (0,0,255)


cv2.imshow('one',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-50**
## Corner Dtection (Shi-Tomasi Corner Detection)

In [21]:
import cv2
import numpy as np

In [27]:
img = cv2.imread('picture/corrner.png')
gr = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cr = cv2.goodFeaturesToTrack(gr,30,0.01,20)
cr = np.int64(cr)

for i in cr:
    x,y = i.ravel()
    cv2.circle(img,(x,y),5,(0,0,255),-1)



cv2.imshow('one',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-51**
## Object Dtection Using Haar-Cascade (Face Detection)

In [1]:
import cv2
import numpy as np

In [ ]:
img = cv2.imread('picture/harris.jpg')
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
f = cv2.CascadeClassifier("path of 'harrcascade_frontalface_default.xml'")

d = f.detectMultiScale(gry,1.3,2)

for (x,y,w,h) in d:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)


cv2.imshow('one',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-52**
## Displaying Coordinates and color code of the points clicked on the image

In [6]:
import cv2
import numpy as np

In [18]:
def click_b(event,x,y,f,p):
    if event == cv2.EVENT_LBUTTONDOWN:
        s = f"{x},{y}"
        cv2.putText(img,s,(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,0))
        cv2.imshow('wscube',img)

    elif event == cv2.EVENT_RBUTTONDOWN:
        b = img[y,x,0]
        g = img[y,x,1]
        r = img[y,x,2]
        s = f"{b},{g},{r}"
        cv2.putText(img,s,(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,255))
        cv2.imshow('wscube',img)
        





img  = cv2.imread('picture/circle1.png')
img = cv2.resize(img,(500,500))


cv2.imshow('wscube',img)


cv2.setMouseCallback('wscube',click_b)



cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-53**
## Play a video in reverse mode

In [19]:
import cv2
import numpy as np

In [26]:
cap = cv2.VideoCapture('picture/video1.mp4')

c = 1
while cap.isOpened():
    r,f = cap.read()
    if r == True:
        file_name = r"F:\Open cv\picture\img\demo"+str(c)+".jpg"
        cv2.imwrite(file_name,f)
        c = c+1
        cv2.imshow('one',f)
        if cv2.waitKey(55) & 0xff == ord('q'):
            break
    else:
        break



cap.release()
cv2.destroyAllWindows()

In [3]:

cap = cv2.VideoCapture('picture/new_video.mp4')
l =[]
c = 1
while cap.isOpened():
    r,f = cap.read()
    if r == True:
        file_name = r"F:\Open cv\picture\img\demo"+str(c)+".jpg"
        l.append(file_name)
        cv2.imwrite(file_name,f)
        c = c+1
        cv2.imshow('one',f)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break

l.reverse()

for i in l:
    img_new = cv2.imread(i)
    cv2.imshow('two',img_new)
    if cv2.waitKey(25) & 0xff == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()

# **class-54**
## Vehicle Detection in a Video Frame

In [1]:
import cv2
import numpy as np

In [7]:

cap = cv2.VideoCapture('picture/detection.mp4')

while cap.isOpened():
    r,f = cap.read()
    if r == True:
        gry = cv2.cvtColor(f,cv2.COLOR_BGR2GRAY)
        car = cv2.CascadeClassifier("picture/cars.xml")
        cars = car.detectMultiScale(gry,1.2,3)

        for (x,y,w,h) in cars:
            cv2.rectangle(f,(x,y),(x+w,y+h),(0,0,255),3)


        cv2.imshow('one',f)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

In [19]:
img = cv2.imread('picture/carde.jpg')

gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

car1 = cv2.CascadeClassifier('picture/cars.xml')

cars1 = car1.detectMultiScale(gry,1.2,2)

for (x,y,w,h) in cars1:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)

cv2.imshow('one',img)
cv2.waitKey(0) 
cv2.destroyAllWindows()

# **class - 55**
## Smile and Eye detection

In [1]:
import cv2
import numpy as np

In [44]:
img = cv2.imread('picture/harris.jpg')
img = cv2.resize(img,(500,600))
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

sm = cv2.CascadeClassifier('picture/haarcascade_smile.xml')
fc = cv2.CascadeClassifier('picture/haarcascade_frontalface_default.xml')
f = fc.detectMultiScale(gry,1.3,3)


for (x,y,w,h) in f:
    roi_gry = gry[y:y+h,x:x+w]
    roi_img = img[y:y+h,x:x+w]
    s = sm.detectMultiScale(roi_gry,2.5,5)
    for (xs,ys,ws,hs) in s:
        cv2.rectangle(roi_img,(xs,ys),(xs+ws,ys+hs),(0,0,255),2)




cv2.imshow('one',img)
# cv2.imshow('two',roi_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [43]:
img = cv2.imread('picture/harris.jpg')
img = cv2.resize(img,(500,600))
gry = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

sm = cv2.CascadeClassifier('picture/haarcascade_eye.xml')
fc = cv2.CascadeClassifier('picture/haarcascade_frontalface_default.xml')
f = fc.detectMultiScale(gry,1.3,3)


for (x,y,w,h) in f:
    roi_gry = gry[y:y+h,x:x+w]
    roi_img = img[y:y+h,x:x+w]
    s = sm.detectMultiScale(roi_gry,2.5,3)
    for (xs,ys,ws,hs) in s:
        cv2.rectangle(roi_img,(xs,ys),(xs+ws,ys+hs),(0,0,255),2)




cv2.imshow('one',img)
# cv2.imshow('two',roi_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# **class-56**
## Pedestrian Detection from a streaming video

In [45]:
import cv2
import numpy as np

In [55]:
cap = cv2.VideoCapture('picture/walk1.mp4')

while cap.isOpened():
    r,f = cap.read()
    if r == True:
        f = cv2.resize(f,(900,600))
        gry = cv2.cvtColor(f,cv2.COLOR_BGR2GRAY)
        hm = cv2.CascadeClassifier(r"picture/haarcascade_fullbody.xml")
        h = hm.detectMultiScale(gry,1.2,3)

        for (x,y,w,h) in h:
            cv2.rectangle(f,(x,y),(x+w,y+h),(0,0,255),3)

        cv2.imshow('one',f)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break
cap.release()
cv2.destroyAllWindows()

# **class-57**
## MediaPipe

In [1]:
import cv2
import mediapipe as mp

In [ ]:
mp_face_det = mp.solutions.face_detection
mp_draw = mp.solutions.drawing_utils

In [ ]:
face_dect = mp_face_det.FaceDetection(min_detection_confidence=1,model_selection=0) 

cap = cv2.VideoCapture(0)
while cap.isOpened():
    r,f = cap.read()
    f = cv2.flip(f,1)
    f = cv2.cvtColor(f,cv2.COLOR_BGR2RGB)
    result = face_dect.process(f)
    f = cv2.cvtColor(f,cv2.COLOR_RGB2BGR)
    if r == True:
        for cr in result.detections:
            mp_draw.draw_detection(f,cr)

        cv2.imshow('one',f)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break

    else:
        break


cap.release()

cv2.destroyAllWindows()



# **class-58**
## Hand Tracking

In [1]:
import cv2
import mediapipe as mp

In [ ]:
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

cap = cv2.VideoCapture(0)
p = mp_hands.Hands(model_complexity=0,max_num_hands =2,min_detection_confidence = 0.5 )

while cap.isOpened():
    r,frame = cap.read()
    if r == True:
        frame = cv2.flip(frame,1)
        img = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        result = p.process(img)
        frame = cv2.cvtColor(frame,cv2.COLOR_RGB2BGR)
        if result.multi_hand_landmarks:
            for hand_landmark in result.multi_hand_landmarks:
                mp_drawing.draw_landmarks(frame,hand_landmark,mp_hands.HAND_CONNECTIONS)


        cv2.imshow('one',frame)
        if cv2.waitKey(25) & 0xff == ord('q'):
            break
    else:
        break

cap.release()
cv2.destroyAllWindows()